<?php

namespace Database\Seeders;

use App\Models\Quiz;
use App\Models\QuizOption;
use App\Models\QuizQuestion;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuizQuestionsSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {

            $quizzes = [

                // =====================================================================
                //  A1
                // =====================================================================
                'A1' => [
                    'title'                => 'Deutsch Einstufungstest A1',
                    'description'          => 'Grundlagen: einfache Sätze, Alltag, Vorstellen, Fragen beantworten.',
                    'time_limit_seconds'   => 900,
                    'questions_per_attempt' => 15,
                    'questions'            => [
                        [
                            'question_text' => 'Ich ____ einen Hund.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 1,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'habe',    'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'bin',     'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'hat',     'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Wie ____ du?',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 2,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'heißen',  'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'heißt',   'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'heiße',   'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Das ist ____ Auto.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 3,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'mein',    'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'meine',   'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'meiner',  'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Wir ____ nach Berlin.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 4,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'fahrt',   'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'fahren',  'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'fährt',   'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => '____ kostet der Tee?',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 5,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'Was',     'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'Wie',     'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'Wer',     'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Der Film ist ____.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 6,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'gut',     'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'gute',    'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'gutes',   'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Ich trinke ____ Kaffee.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 7,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'kein',    'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'keinen',  'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'keine',   'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Das Wetter ist heute ____.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 8,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'schön',   'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'schöne',  'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'schöner', 'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Er arbeitet ____ einem Büro.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 9,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'in',      'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'auf',     'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'zu',      'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Wir gehen ____ Kino.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 10,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'ins',     'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'im',      'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'in der',  'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Der Tisch ____ groß.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 11,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'sind',    'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'bist',    'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'ist',     'is_correct' => true,  'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => '____ kommst du? — Aus der Schweiz.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 12,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'Wo',      'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'Woher',   'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'Wohin',   'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Meine Schwester ____ 15 Jahre alt.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 13,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'habe',    'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'hat',     'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'ist',     'is_correct' => true,  'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Ich möchte ____ Orangensaft.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 14,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'ein',     'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'eine',    'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'einen',   'is_correct' => true,  'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Das ist mein Bruder. ____ Name ist Paul.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 15,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'Sein',    'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'Ihr',     'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'Mein',    'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Gestern ____ ich im Park.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 16,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'war',     'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'bin',     'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'habe',    'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Die Kinder spielen ____ Fußball.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 17,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'der',     'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'die',     'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => '—',       'is_correct' => true,  'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Kannst du ____ bitte helfen?',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 18,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'mich',    'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'mir',     'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'dich',    'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Hast du Geschwister? — Ja, ich habe ____ Bruder.',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 19,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'einer',   'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'einen',   'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'ein',     'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Wie spät ____ es?',
                            'difficulty'    => 1,
                            'points' => 1,
                            'sort_order' => 20,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'haben',   'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'ist',     'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'sind',    'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                    ],
                ],

                // =====================================================================
                //  A2
                // =====================================================================
                'A2' => [
                    'title'                => 'Deutsch Einstufungstest A2',
                    'description'          => 'Erweiterte Grundlagen: Alltagssituationen, einfache Grammatik, kurze Texte.',
                    'time_limit_seconds'   => 1080,
                    'questions_per_attempt' => 15,
                    'questions'            => [
                        [
                            'question_text' => 'Letzte Woche habe ich viel ____.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 1,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'arbeitete', 'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'gearbeitet', 'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'arbeite',   'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Im Sommer ist es ____ als im Winter.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 2,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'wärmer',    'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'warm',      'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'am wärmsten', 'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Wir fahren mit ____ Zug.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 3,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'den',       'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'dem',       'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'das',       'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Ich interessiere mich ____ Kunst.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 4,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'auf',       'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'über',      'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'für',       'is_correct' => true,  'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Wann ____ du nach Hause gekommen?',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 5,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'hast',      'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'bist',      'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'hat',       'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Das ist das Haus, in ____ ich wohne.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 6,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'der',       'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'dem',       'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'den',       'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Du solltest mehr Wasser ____.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 7,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'trinken',   'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'trinkst',   'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'trinkt',    'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Sie hat ____ Brille vergessen.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 8,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'ihre',      'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'ihr',       'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'seiner',    'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Wenn es regnet, bleiben wir ____ Hause.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 9,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'nach',      'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'zu',        'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'ins',       'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Das ist der Mann, ____ mir geholfen hat.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 10,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'der',       'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'dem',       'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'den',       'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Darf ich ____ Handy benutzen?',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 11,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'dein',      'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'deine',     'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'deiner',    'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Wir haben ____ Hunger.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 12,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'großes',    'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'große',     'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'großen',    'is_correct' => true,  'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Der Film dauert ____ eineinhalb Stunden.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 13,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'vor',       'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'für',       'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => '—',         'is_correct' => true,  'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Ich habe morgen eine Prüfung, ____ lerne ich heute Abend viel.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 14,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'obwohl',    'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'deshalb',   'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'trotzdem',  'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Könnten Sie mir bitte ____ Weg zeigen?',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 15,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'der',       'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'den',       'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'die',       'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Es ist wichtig, regelmäßig Sport ____.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 16,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'zu machen', 'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'machen',    'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'machst',    'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Wir sehen uns ____ nächste Woche.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 17,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'in',        'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'am',        'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => '—',         'is_correct' => true,  'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Ich bleibe zu Hause, ____ ich krank bin.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 18,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'aber',      'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'weil',      'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'deshalb',   'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Die Fenster werden jeden Tag ____.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 19,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'geputzt',   'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'putzen',    'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'putzt',     'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Ich ____ gestern zu Hause ____.',
                            'difficulty'    => 2,
                            'points' => 2,
                            'sort_order' => 20,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'habe / geblieben', 'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'bin / geblieben',  'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'habe / bleiben',   'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                    ],
                ],

                // =====================================================================
                //  B1
                // =====================================================================
                'B1' => [
                    'title'                => 'Deutsch Einstufungstest B1',
                    'description'          => 'Mittlere Stufe: komplexere Sätze, grammatikalische Strukturen, Alltag und Beruf.',
                    'time_limit_seconds'   => 1200,
                    'questions_per_attempt' => 15,
                    'questions'            => [
                        [
                            'question_text' => 'Wenn ich mehr Zeit ____, würde ich verreisen.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 1,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'habe',     'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'hätte',    'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'hatte',    'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Sie ist die Frau, ____ mir geholfen hat.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 2,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'die',      'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'der',      'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'welche',   'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Ich bin zu spät gekommen, ____ ich den Bus verpasst habe.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 3,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'trotzdem', 'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'weil',     'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'obwohl',   'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Das sind die Touristen, ____ Marrakesch gefallen hat.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 4,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'die',      'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'denen',    'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'den',      'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Er tut so, ____ er nichts wüsste.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 5,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'als ob',   'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'als',      'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'wie',      'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Darf ich dir ____ Rat geben?',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 6,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'ein',      'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'einen',    'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'einer',    'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Das ist das schönste Kleid, ____ sie je getragen hat.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 7,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'das',      'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'was',      'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'dass',     'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Ich erinnere mich nicht ____ den Namen.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 8,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'an',       'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'auf',      'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'für',      'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Die Hausaufgaben ____ gestern von dem Lehrer kontrolliert.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 9,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'werden',   'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'wurden',   'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'wird',     'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Sie spricht Deutsch ohne ____ Fehler.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 10,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'jeden',    'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'einen',    'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'einem',    'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Ich bin überzeugt, dass er Recht ____.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 11,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'hat',      'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'ist',      'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'wird',     'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Je mehr man lernt, desto ____ wird man.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 12,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'klüger',   'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'klug',     'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'am klügsten', 'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Hätten Sie etwas ____? — Nein, danke.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 13,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'anders',   'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'anderer',  'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'anderes',  'is_correct' => true,  'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Der Vortrag wurde ____ verstanden.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 14,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'schlecht', 'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'schlechte', 'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'schlechter', 'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Es lohnt sich, dieses Buch ____ lesen.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 15,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'zu',       'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => '—',        'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'für',      'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Sie hätte besser aufpassen ____.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 16,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'sollen',   'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'sollte',   'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'gesollt',  'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Das ist der Schlüssel, den ich gesucht ____.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 17,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'bin',      'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'habe',     'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'werden',   'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Nach der Arbeit geht er immer ____.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 18,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'schwimmen', 'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'schwimmt', 'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'geschwommen', 'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Er ist nicht nur intelligent, ____ auch fleißig.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 19,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'aber',     'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'sondern',  'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'und',      'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Das ist typisch ____ ihn.',
                            'difficulty'    => 3,
                            'points' => 3,
                            'sort_order' => 20,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'von',      'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'für',      'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'über',     'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                    ],
                ],

                // =====================================================================
                //  B2
                // =====================================================================
                'B2' => [
                    'title'                => 'Deutsch Einstufungstest B2',
                    'description'          => 'Oberstufe: komplexe Texte, idiomatische Ausdrücke, berufliche und akademische Sprache.',
                    'time_limit_seconds'   => 1500,
                    'questions_per_attempt' => 15,
                    'questions'            => [
                        [
                            'question_text' => 'Welcher Satz ist korrekt?',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 1,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'Obwohl er war müde, ging er arbeiten.', 'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'Obwohl er müde war, ging er arbeiten.', 'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'Obwohl war er müde, ging er arbeiten.', 'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Die Kommunikation zwischen den Abteilungen lässt zu wünschen ____.',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 2,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'übrig',     'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'haben',     'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'lassen',    'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => '____ allen Bemühungen gelang es ihm nicht.',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 3,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'Trotz',     'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'Wegen',     'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'Ohne',      'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Was bedeutet „ins kalte Wasser springen“?',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 4,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'schwimmen lernen',                 'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'spontan etwas Schwieriges wagen',  'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'Angst vor Wasser haben',           'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Der Antrag muss bis spätestens Freitag ____ werden.',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 5,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'stellte',   'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'einreichen', 'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'eingereicht', 'is_correct' => true, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Man muss in der Lage sein, zwischen Fakten und Meinungen zu ____.',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 6,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'unterscheiden', 'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'teilen',     'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'trennen',    'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => '____ des starken Regens fand die Veranstaltung statt.',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 7,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'Trotz',     'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'Wegen',     'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'Aufgrund',  'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Was bedeutet „zwei Fliegen mit einer Klappe schlagen“?',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 8,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'zwei Probleme gleichzeitig lösen', 'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'Tiere jagen',                      'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'einen Fehler machen',              'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Ergänzen Sie das Sprichwort: „Aller Anfang ist ____“',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 9,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'schwer',    'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'einfach',   'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'gefährlich', 'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Man sollte Verantwortung für seine Fehler ____.',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 10,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'übernehmen', 'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'ziehen',    'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'geben',     'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Im Vergleich zum Vorjahr sind die Zahlen leicht ____.',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 11,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'gefallen',  'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'gestiegen', 'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'aufgestanden', 'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Synonym für „sich bemühen“:',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 12,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'sich anstrengen', 'is_correct' => true, 'sort_order' => 0],
                                ['option_text' => 'sich beschweren', 'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'sich wundern', 'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Die Firma hat Insolvenz ____.',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 13,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'gemacht',   'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'angemeldet', 'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'gestellt',  'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Es ist davon auszugehen, dass die Preise weiter ____.',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 14,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'steigen werden', 'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'gestiegen',      'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'gestiegen sind', 'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Viele Menschen leiden ____ Stress.',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 15,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'an',        'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'unter',     'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'mit',       'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Was bedeutet „etwas in Kauf nehmen“?',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 16,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'etwas akzeptieren, obwohl es Nachteile hat', 'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'etwas billig kaufen',                        'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'etwas zurückgeben',                          'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Was bedeutet das Sprichwort „Übung macht den Meister“?',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 17,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'Talent ist wichtiger als Arbeit',           'is_correct' => false, 'sort_order' => 0],
                                ['option_text' => 'Durch regelmäßiges Training wird man besser', 'is_correct' => true,  'sort_order' => 1],
                                ['option_text' => 'Meister arbeiten ohne Übung',                'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Das Unternehmen befindet sich derzeit in einer schwierigen ____.',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 18,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'Lage',      'is_correct' => true,  'sort_order' => 0],
                                ['option_text' => 'Zustand',   'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'Ort',       'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                        [
                            'question_text' => 'Die Diskussion drehte sich lange um eine ____ Frage.',
                            'difficulty'    => 4,
                            'points' => 4,
                            'sort_order' => 19,
                            'media_type'    => 'none',
                            'media_caption' => null,
                            'options'       => [
                                ['option_text' => 'nebensächliche', 'is_correct' => true, 'sort_order' => 0],
                                ['option_text' => 'nebenbei',     'is_correct' => false, 'sort_order' => 1],
                                ['option_text' => 'nächste',      'is_correct' => false, 'sort_order' => 2],
                            ],
                        ],
                    ],
                ],
            ];

            // Clear existing data
            QuizOption::query()->forceDelete();
            QuizQuestion::query()->forceDelete();
            Quiz::query()->forceDelete();

            foreach ($quizzes as $code => $quizData) {
                $quiz = Quiz::create([
                    'code' => $code,
                    'title' => $quizData['title'],
                    'description' => $quizData['description'],
                    'time_limit_seconds' => $quizData['time_limit_seconds'],
                    'questions_per_attempt' => $quizData['questions_per_attempt'],
                ]);

                foreach ($quizData['questions'] as $questionData) {
                    $question = $quiz->questions()->create([
                        'question_text' => $questionData['question_text'],
                        'difficulty' => $questionData['difficulty'],
                        'points' => $questionData['points'],
                        'sort_order' => $questionData['sort_order'],
                        'media_type' => $questionData['media_type'],
                        'media_caption' => $questionData['media_caption'],
                    ]);

                    foreach ($questionData['options'] as $optionData) {
                        $question->options()->create([
                            'option_text' => $optionData['option_text'],
                            'is_correct' => $optionData['is_correct'],
                            'sort_order' => $optionData['sort_order'],
                        ]);
                    }
                }
            }
        });
    }
}
